# Validate that PR titles are prefixed with one of our accepted labels
name: "PR Title Checker"
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - auto_merge_enabled

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title validity
        if: "!contains(github.event.pull_request.title, '[FEATURE]') && !contains(github.event.pull_request.title, '[BUGFIX]') && !contains(github.event.pull_request.title, '[DOCS]') && !contains(github.event.pull_request.title, '[MAINTENANCE]') && !contains(github.event.pull_request.title, '[CONTRIB]') && !contains(github.event.pull_request.title, '[RELEASE]')"
        run: |
          echo "Invalid PR title - please prefix with one of: [FEATURE] | [BUGFIX] | [DOCS] | [MAINTENANCE] | [CONTRIB] | [RELEASE]"
          exit 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
